name: CI

on:
  create: # when tags are created
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build_Windows:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build Project
      run: dotnet build -c Release --no-restore src

    - name: Build Packages
      run: dotnet pack src/ImGuiSharp -c Release --no-restore --no-build
    - name: List Packages
      run: ls -l bin\Release\ImGuiSharp\

    - name: Publish to nuget.org
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet nuget push bin\Release\ImGuiSharp\*.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_KEY}}
